import manifest from "./imageManifest.json";

type Entry = { v: string; w: number | null; h: number | null };
const data = manifest as Record<string, Entry>;

/**
 * Appends a content-hash query param so replacing a /public image's bytes
 * (even under the same filename) is a new URL — no browser or CDN cache
 * anywhere can serve stale bytes for it, and no one has to remember to
 * rename the file. The hash is regenerated by scripts/build-image-manifest.mjs
 * on every build, so this requires no manual upkeep.
 */
export function versionedSrc(src: string): string {
  const entry = data[src];
  return entry ? `${src}?v=${entry.v}` : src;
}

/** The image's real aspect ratio (width / height), if known. */
export function imageAspect(src: string): number | undefined {
  const entry = data[src];
  if (!entry || !entry.w || !entry.h) return undefined;
  return entry.w / entry.h;
}
